// Generated by sync-library.mjs
window.PROMPTER_LIBRARY = [
  {
    "title": "Intro",
    "fileName": "intro.txt",
    "description": "Saved script from intro.txt",
    "content": "Hi, I’m Ritik Dutta. I’m a Data Scientist and AI Engineer with 4 years of experience building GenAI, RAG, and computer vision systems on AWS and GCP.\n\nCurrently, I’m working as a Tech Lead at Animal Badge Marketing, where I build LLM-based assistants, RAG pipelines, and scalable backend systems. I also developed a workforce management platform that improved operational efficiency by 30%.\n\nPreviously, I worked at iNeuron as a Computer Vision Engineer and Full Stack Data Scientist, where I built real-time face recognition and object detection systems that reduced operational costs by around 80%.\n\nI’ve also worked on GenAI-focused projects with organizations like NavGurukul and Bot Consulting. Overall, I enjoy building end-to-end AI systems that create real business impact.\n"
  }
];
