// Generated by sync-library.mjs
window.PROMPTER_LIBRARY = [
  {
    "title": "Intro",
    "fileName": "intro.txt",
    "description": "Saved script from intro.txt",
    "content": "Hi, I’m Ritik Dutta. I’m a Data Scientist and AI Engineer with 4 years of experience building GenAI, RAG, and computer vision systems on AWS and GCP.\n\nCurrently, I’m working as a Tech Lead at Animal Badge Marketing, where I build LLM-based assistants, RAG pipelines, and scalable backend systems. I also developed a workforce management platform that improved operational efficiency by 30%.\n\nPreviously, I worked at iNeuron as a Computer Vision Engineer and Full Stack Data Scientist, where I built real-time face recognition and object detection systems that reduced operational costs by around 80%.\n\nI’ve also worked on GenAI-focused projects with organizations like NavGurukul and Bot Consulting. Overall, I enjoy building end-to-end AI systems that create real business impact.\n"
  },
  {
    "title": "Sprints For Edtech",
    "fileName": "sprints_for_edtech.txt",
    "description": "Saved script from sprints_for_edtech.txt",
    "content": "We’ll run this in tight weekly sprints and keep the scope disciplined around MVP. Week 0 is just setup—repo, base backend, Postgres and Redis wired, auth scaffold, and a deployable skeleton. Sprint 1 is core models and auth—users, courses, chapters, basic APIs and UI shell. Sprint 2 we lock content—MCQs, key points, chapter APIs, and seed data so the system actually has substance. Sprint 3 is the MCQ engine—attempts, wrong question tracking, retry flow, and caching hot reads. Sprint 4 is the critical piece—the RAG-based doubt solver with answer reuse; we don’t hit the LLM blindly, we check similarity first to control cost and latency. Sprint 5 we layer progress tracking and a usable dashboard—stats, completion, basic insights. Sprint 6 is test system—chapter tests, submissions, scoring. Sprint 7 we bring monetization—plans, usage limits, paywall triggers, enforced via Redis for speed. Sprint 8 is polish—saved doubts, daily tasks, tone control in AI responses so it doesn’t sound generic. Sprint 9 is stability—queues for heavy ops, rate limiting, logging, deploy behind Nginx. Last sprint is buffer—fixes and performance tuning. No overengineering—Postgres as source of truth, Redis aggressively for cache and limits, queue for async jobs, and we scale horizontally when needed, not before. The goal is a working, paid MVP in ~6–8 weeks, not a perfect system."
  }
];
