import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const LIBRARY_DIR = "library";

function formatTitle(fileName) {
  return fileName
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (match) => match.toUpperCase());
}

async function main() {
  const libraryPath = path.join(process.cwd(), LIBRARY_DIR);
  await mkdir(libraryPath, { recursive: true });

  const directoryEntries = await readdir(libraryPath, { withFileTypes: true });
  const textFiles = directoryEntries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".txt"))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const libraryEntries = [];

  for (const fileName of textFiles) {
    const content = await readFile(path.join(libraryPath, fileName), "utf8");

    if (!content.trim()) {
      continue;
    }

    libraryEntries.push({
      title: formatTitle(fileName),
      fileName,
      description: `Saved script from ${fileName}`,
      content,
    });
  }

  const output = `// Generated by sync-library.mjs\nwindow.PROMPTER_LIBRARY = ${JSON.stringify(
    libraryEntries,
    null,
    2
  )};\n`;

  await writeFile("library-data.js", output, "utf8");
  console.log(
    `Synced ${libraryEntries.length} script(s) from ${LIBRARY_DIR}/ to library-data.js`
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
