import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const LIBRARY_DIR = "library";
const LIBRARY_EXTENSIONS = new Set([".txt", ".md", ".json"]);

function formatTitle(fileName) {
  return fileName
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (match) => match.toUpperCase());
}

async function main() {
  const libraryPath = path.join(process.cwd(), LIBRARY_DIR);
  await mkdir(libraryPath, { recursive: true });

  const directoryEntries = await readdir(libraryPath, { withFileTypes: true });
  const libraryFiles = directoryEntries
    .filter((entry) => {
      if (!entry.isFile()) {
        return false;
      }

      return LIBRARY_EXTENSIONS.has(path.extname(entry.name).toLowerCase());
    })
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const libraryEntries = [];

  for (const fileName of libraryFiles) {
    const extension = path.extname(fileName).toLowerCase();
    const content = await readFile(path.join(libraryPath, fileName), "utf8");

    if (!content.trim()) {
      continue;
    }

    if (extension === ".json") {
      const parsed = JSON.parse(content);

      if (!parsed || typeof parsed.content !== "string" || !parsed.content.trim()) {
        continue;
      }

      libraryEntries.push({
        title:
          typeof parsed.title === "string" && parsed.title.trim()
            ? parsed.title.trim()
            : formatTitle(fileName),
        fileName,
        description:
          typeof parsed.description === "string" && parsed.description.trim()
            ? parsed.description.trim()
            : `Saved script from ${fileName}`,
        content: parsed.content,
      });
      continue;
    }

    libraryEntries.push({
      title: formatTitle(fileName),
      fileName,
      description:
        extension === ".md" ? `Saved markdown script from ${fileName}` : `Saved script from ${fileName}`,
      content,
    });
  }

  const output = `// Generated by sync-library.mjs\nwindow.PROMPTER_LIBRARY = ${JSON.stringify(
    libraryEntries,
    null,
    2
  )};\n`;

  await writeFile("library-data.js", output, "utf8");
  console.log(
    `Synced ${libraryEntries.length} script(s) from ${LIBRARY_DIR}/ to library-data.js`
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
